### ISSUE TITLE
Question: do copy/mirror/backup modes work?

### ISSUE THREAD

**Issue by Googliola** [macdylan/3dp-configs#1]
Found this gem in the start gcode section:

{if physical_printer_preset =~/.*IDEXDupl.*/ || physical_printer_preset =~/.*IDEXCopy.*/ }
  M605 S2 X162 R0 ;IDEX Duplication
{elsif physical_printer_preset =~/.*IDEXMirr.*/}
  M605 S3 ;IDEX Mirror
{elsif physical_printer_preset =~/.*IDEXBack.*/}
  M605 S4 ;IDEX Backup
{endif}

Does it work? and if so, how can it be enabled?

That capability would be a huge improvement!

Thanks a lot for your hard work here!

**Comment by macdylan** [comment]
Add one or more physical printers with these keywords(IDEXMirror/Copy) in their names.
<img width="623" alt="image" src="https://github.com/macdylan/3dp-configs/assets/331506/904d5b43-75ef-4fc8-9424-3ad65dda9d95">

In OrcaSlicer, include these keywords in the name of the Plate settings:
<img width="1192" alt="image" src="https://github.com/macdylan/3dp-configs/assets/331506/b41ffef1-04f6-4f7b-84ee-e719ed020539">

**Comment by Googliola** [comment]
Thanks a lot! Working now.

Some notes:

1. Turns out you need to restart Prusaslicer after creating the new Physical Printer or it wont be picked up in the gcode.
2. If I change from IDEXCopy to IDEXMirror, the gcode does NOT get re-sliced and the Physical Printer will still be the same (IDEXCopy in this case, check the gcode). Probably related to note 1. PrusaSlicer 2.6.0
3. Copy mode does not work. Mirror mode does. Will open a separate issue soon.

**Comment by macdylan** [comment]
> 2\. If I change from IDEXCopy to IDEXMirror, the gcode does NOT get re-sliced and the Physical Printer will still be the same (IDEXCopy in this case, check the gcode). Probably related to note 1. PrusaSlicer 2.6.0

All we need to do is move the model a little and re-slice it 🤣

**Comment by Googliola** [comment]
> All we need to do is move the model a little and re-slice it 🤣

That's what I thought too. But nope. 
You need to change the printer to some other model or maybe just a printer with different Print Settings.
If the plate is _reloaded_ , then you are fine.
