### ISSUE TITLE
Orca Configs for Snapmaker J1 have long purges/retractions

### ISSUE THREAD

**Issue by KyGunsAndRadio** [macdylan/3dp-configs#3]
Downloaded latest OrcaSlicer v1.9.0. I noticed this release was supposed to include your latest profiles, which is great. But, the start/end gcode contain multiple long purges and a long retraction at the end. These aren't needed for an IDEX printer. The purges just make a mess in the printer, but the retraction jammed up my extruder gears on the very first print with this version. These were not present in previous versions.

Sure it's easy enough to comment them out, but is there a reason these were added that I'm not considering?

![Screenshot from 2024-02-02 14-25-37](https://github.com/macdylan/3dp-configs/assets/89168030/bace5c27-9d62-4794-9f32-b896e503f3f5)

**Comment by KyGunsAndRadio** [comment]
So, I did find your explanation of the changes in the readme. I can understand the purges, but in my case the retraction definitely caused issues. Also, for some reason the right nozzle didn't return back to the silicone stop after the initial purge. I reverted back to your 20230731 gcode as it worked perfectly for me.

**Comment by le-avion** [comment]
I am having the same VERY long purge before the print begins. This is on the Prusaslicer with the Snapmaker 2.0 A350. The readme talks about 4-8 cm but what I am getting is more like a meter. Not sure how to fix it. Where is this defined?

**Comment by macdylan** [comment]
Sorry for the late reply, I'm currently spending the Chinese New Year holiday.

I often use IDEX to print different filaments such as PLA/PVA/HIPS/ABS/PA-CF/PET/PETG, and I prefer to completely flush the nozzle when switching filaments, In addition since the filament are pulled away from the nozzle at the end of printing, more extrusion is needed to fill this space.

I understand the extra cost of flush, and messy. I'm working on improving and testing this, and will release a test version in mid-March.

**Comment by KyGunsAndRadio** [comment]
@macdylan Thanks for the followup and for all your work on Snapmaker printers. My J1 would probably not get used if it wasn't for your profiles and sm2uploader.

@le-avion The purges are coded directly in the Start G-code. Look under the printer settings and Machine Gcode. Make sure advanced settings are enabled. You will see a few lines like G1 E50 (may not be exact). Those are the purges. The retraction is in the End Gcode.

**Comment by macdylan** [comment]
Hey guys, a new version has been released:
https://github.com/macdylan/3dp-configs/releases/tag/20240429_6b549a3

I've been testing it for a while, please give it a try:
![IMG_6791](https://github.com/macdylan/3dp-configs/assets/331506/ca5c8c85-e163-46fe-9450-ed38f3c1efc2)
![IMG_6792](https://github.com/macdylan/3dp-configs/assets/331506/757866e4-bbd4-46e3-8e7b-b57c564ff626)
